const DummyData = [
    {
      id: "1",
      jobTitle: "Fullstack Developer Job",
      companyName: "The New Angle | Jaipur, India",
      tags1: "Javascript",
      tags2: "Ajax",
      tags3: "React.js",
      tags4: "Ruby",
      tags5: "Ruby on Rails",
      tags6:" PostGreSQL",
      offer: "₹ 3 LPA - 4 LPA",
      start: "Immediate",
      open: "1",
      exp: " 10 years experience",
    },
    {
      id: "2",
      jobTitle: "Web stack developer ",
      companyName: "SH infotech",
      tags1: "React.js",
      tags2: "React.js",
      tags3: "React.js",
      tags4: "React.js",
      tags5: "React.js",
      offer: "Offer : 15 lpa",
      start: " Start Date: 15-06-24",
      exp: " 10 years experience",
    },
    {
      id: "3",
      jobTitle: "PHP developer ",
      companyName: "SH infotech",
      tags1: "React.js",
      tags2: "React.js",
      tags3: "React.js",
      tags4: "React.js",
      tags5: "React.js",
      offer: "Offer : 15 lpa",
      start: " Start Date: 15-06-24",
      exp: " 10 years experience",
    },
    {
      id: "4",
      jobTitle: "PHP developer ",
      companyName: "SH infotech",
      tags1: "React.js",
      tags2: "React.js",
      tags3: "React.js",
      tags4: "React.js",
      tags5: "React.js",
      offer: "Offer : 15 lpa",
      start: " Start Date: 15-06-24",
      exp: " 10 years experience",
    },
    {
      id:"5",
      jobTitle: "PHP developer ",
      companyName: "SH infotech",
      tags1: "React.js",
      tags2: "React.js",
      tags3: "React.js",
      tags4: "React.js",
      tags5: "React.js",
      offer: "Offer : 15 lpa",
      start: " Start Date: 15-06-24",
      exp: " 10 years experience",
    },
  ];

  export default DummyData